# 円ドル為替レート株価（日足）

In [1]:
import matplotlib.pyplot as plt
import mplfinance as mpf
import numpy as np
import pandas as pd
import yfinance as yf

symbol = 'USDJPY=X'
ticker = yf.Ticker(symbol)

df = ticker.history(period='1d', interval='1m')
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2025-03-07 00:00:00+00:00,148.145004,148.162003,148.059998,148.059998,0,0.0,0.0
2025-03-07 00:01:00+00:00,148.061996,148.074005,147.994995,148.020004,0,0.0,0.0
2025-03-07 00:02:00+00:00,148.018005,148.024002,147.945999,147.947006,0,0.0,0.0
2025-03-07 00:03:00+00:00,147.953003,147.966995,147.944000,147.957993,0,0.0,0.0
2025-03-07 00:04:00+00:00,147.964005,147.975998,147.878998,147.893997,0,0.0,0.0
...,...,...,...,...,...,...,...
2025-03-07 21:55:00+00:00,148.005997,148.033005,147.998993,148.029999,0,0.0,0.0
2025-03-07 21:56:00+00:00,148.018997,148.041000,147.996002,147.996002,0,0.0,0.0
2025-03-07 21:57:00+00:00,148.014008,148.048996,148.007004,148.046997,0,0.0,0.0
2025-03-07 21:58:00+00:00,148.035995,148.050995,148.001007,148.001007,0,0.0,0.0
2025-03-07 21:59:00+00:00,148.024002,148.029999,147.994003,148.018005,0,0.0,0.0