# 円ドル為替レート株価（日足）

In [1]:
import matplotlib.pyplot as plt
import mplfinance as mpf
import numpy as np
import pandas as pd
import yfinance as yf

symbol = 'USDJPY=X'
ticker = yf.Ticker(symbol)

df = ticker.history(period='1d', interval='1m')
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2025-01-24 00:00:00+00:00,156.132996,156.173004,156.100006,156.113998,0,0.0,0.0
2025-01-24 00:01:00+00:00,156.112000,156.130005,156.098007,156.108002,0,0.0,0.0
2025-01-24 00:02:00+00:00,156.108002,156.108994,156.061005,156.061005,0,0.0,0.0
2025-01-24 00:03:00+00:00,156.063995,156.067001,156.041000,156.048996,0,0.0,0.0
2025-01-24 00:04:00+00:00,156.052002,156.056000,156.022003,156.029007,0,0.0,0.0
...,...,...,...,...,...,...,...
2025-01-24 21:55:00+00:00,155.936005,155.970993,155.921997,155.970993,0,0.0,0.0
2025-01-24 21:56:00+00:00,155.960999,155.983002,155.944000,155.962006,0,0.0,0.0
2025-01-24 21:57:00+00:00,155.957993,155.977005,155.942001,155.953003,0,0.0,0.0
2025-01-24 21:58:00+00:00,155.970001,156.005997,155.940002,155.964005,0,0.0,0.0
2025-01-24 21:59:00+00:00,155.964005,155.983994,155.919998,155.919998,0,0.0,0.0