# 円ドル為替レート株価（日足）

In [1]:
import matplotlib.pyplot as plt
import mplfinance as mpf
import numpy as np
import pandas as pd
import yfinance as yf

symbol = 'USDJPY=X'
ticker = yf.Ticker(symbol)

df = ticker.history(period='1d', interval='1m')
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2025-02-21 00:00:00+00:00,149.475006,149.630997,149.466003,149.600998,0,0.0,0.0
2025-02-21 00:01:00+00:00,149.598999,149.671997,149.585999,149.643997,0,0.0,0.0
2025-02-21 00:02:00+00:00,149.638000,149.653000,149.606003,149.634995,0,0.0,0.0
2025-02-21 00:03:00+00:00,149.638000,149.675995,149.619003,149.664001,0,0.0,0.0
2025-02-21 00:04:00+00:00,149.667999,149.677002,149.606003,149.623001,0,0.0,0.0
...,...,...,...,...,...,...,...
2025-02-21 21:51:00+00:00,149.330002,149.332001,149.283997,149.324997,0,0.0,0.0
2025-02-21 21:52:00+00:00,149.324005,149.341995,149.317993,149.332001,0,0.0,0.0
2025-02-21 21:53:00+00:00,149.339996,149.343002,149.289001,149.326004,0,0.0,0.0
2025-02-21 21:54:00+00:00,149.324997,149.345001,149.315994,149.324005,0,0.0,0.0
2025-02-21 21:55:00+00:00,149.332993,149.332993,149.332993,149.332993,0,0.0,0.0