# 円ドル為替レート株価（日足）

In [1]:
import matplotlib.pyplot as plt
import mplfinance as mpf
import numpy as np
import pandas as pd
import yfinance as yf

symbol = 'USDJPY=X'
ticker = yf.Ticker(symbol)

df = ticker.history(period='1d', interval='1m')
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2025-03-14 00:00:00+00:00,147.938004,147.973999,147.914993,147.945007,0,0.0,0.0
2025-03-14 00:01:00+00:00,147.942001,147.947998,147.845993,147.847000,0,0.0,0.0
2025-03-14 00:02:00+00:00,147.850006,147.889008,147.848007,147.880005,0,0.0,0.0
2025-03-14 00:03:00+00:00,147.880997,147.916000,147.852005,147.871002,0,0.0,0.0
2025-03-14 00:04:00+00:00,147.869995,147.889999,147.856995,147.869995,0,0.0,0.0
...,...,...,...,...,...,...,...
2025-03-14 21:55:00+00:00,148.610001,148.610001,148.610001,148.610001,0,0.0,0.0
2025-03-14 21:56:00+00:00,148.610001,148.610001,148.610001,148.610001,0,0.0,0.0
2025-03-14 21:57:00+00:00,148.610001,148.610001,148.610001,148.610001,0,0.0,0.0
2025-03-14 21:58:00+00:00,148.610001,148.610001,148.610001,148.610001,0,0.0,0.0
2025-03-14 21:59:00+00:00,148.610001,148.610001,148.610001,148.610001,0,0.0,0.0