# ＭＸＳ読売３３３ ５分足

In [8]:
import sys
sys.path.append('..')

import re

import matplotlib.font_manager as fm
import matplotlib.pyplot as plt
import mplfinance as mpf
import numpy as np
import pandas as pd
import yfinance as yf

from funcs.technical import psar

In [15]:
pattern = re.compile(r'(.+)\.T')

symbol = '348A.T'
ticker = yf.Ticker(symbol)

df = ticker.history(period='1d', interval='1m')
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2025-03-27 09:01:00+09:00,208.0,208.000000,205.000000,205.000000,0,0.0,0.0
2025-03-27 09:02:00+09:00,205.0,207.500000,205.000000,207.500000,320,0.0,0.0
2025-03-27 09:03:00+09:00,207.5,209.399994,204.000000,204.000000,3470,0.0,0.0
2025-03-27 09:04:00+09:00,205.0,209.899994,205.000000,209.000000,5270,0.0,0.0
2025-03-27 09:05:00+09:00,209.0,209.800003,205.100006,209.699997,2580,0.0,0.0
...,...,...,...,...,...,...,...
2025-03-27 15:19:00+09:00,204.5,204.600006,204.500000,204.600006,500,0.0,0.0
2025-03-27 15:20:00+09:00,203.0,203.000000,202.800003,202.800003,800,0.0,0.0
2025-03-27 15:22:00+09:00,203.5,203.500000,203.500000,203.500000,400,0.0,0.0
2025-03-27 15:23:00+09:00,203.5,204.399994,203.500000,204.399994,150,0.0,0.0
2025-03-27 15:24:00+09:00,204.0,204.000000,203.100006,203.100006,330,0.0,0.0

## ローソク足チャートとパラボリック SAR

In [7]:
dict_psar = psar(df)

plt.rcParams["font.size"] = 16
fig = plt.figure(figsize=(12, 6))
#ax = fig.add_subplot(111)
gs = fig.add_gridspec(
    2, 1,
    wspace=0.0, hspace=0.0,
    height_ratios=[3, 1]
)

ax = dict()
for i, axis in enumerate(gs.subplots(sharex='col')):
    ax[i] = axis

apds  = [
    mpf.make_addplot(
        dict_psar['bear'],
        type='scatter',
        marker='o',
        markersize=5,
        color='blue',
        label='downtrend',
        ax=ax[0]
    ),
    mpf.make_addplot(
        dict_psar['bull'],
        type='scatter',
        marker='o',
        markersize=5,
        color='red',
        label='uptrend',
        ax=ax[0]
    ),
] 

mpf.plot(
    df,
    type='candle',
    style='default',
    datetime_format='%H:%M',
    addplot=apds,
    xrotation=0,
    ax=ax[0],
    volume=ax[1],
)

try:
    ax[0].set_title('5 min chart for %s (%s)' % (ticker.info['longName'], symbol))
except KeyError:
    ax[0].set_title('5 min chart for %s' % symbol)

ax[0].grid()
ax[0].legend(loc='best', fontsize=9)

ax[1].grid()


plt.tight_layout()

m = pattern.match(symbol)
if m:
    plt.savefig('5min_chart_%s.png' % m.group(1))
else:
    plt.savefig('5min_chart_%s.png' % symbol)

plt.show()

IndexError: list index out of range

In [4]:
df.tail(2)['Close']

Datetime
2025-03-27 15:15:00+09:00    204.600006
2025-03-27 15:20:00+09:00    203.100006
Name: Close, dtype: float64

In [5]:
df.tail(2)['Close'].diff()

Datetime
2025-03-27 15:15:00+09:00    NaN
2025-03-27 15:20:00+09:00   -1.5
Name: Close, dtype: float64